cache: npm
deploy: 
  github-token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  skip-cleanup: true
  true: 
    branch: master
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
script: "-npm run build"