cache: npm
deploy: 
  github-token: $github_token
  local_dir: build
  provider: pages
  skip-cleanup: true
  true: 
    branch: master
install: 
  - "npm install"
language: node_js
node_js: 
  - "stable"
script: "npm run build"